---
- name: Bootstrap all servers
  import_playbook: jenkins.yml

- name: Configure k3s cluster
  import_playbook: k3s.yml

- name: Install Python 3.12 and Node.js 22 on all servers
  import_playbook: runtimes.yml